### ISSUE TITLE
Cant Run the GUI - Constrained language mode

### ISSUE THREAD

**Issue by Axololtlboy1717171** [ThioJoe/Windows-Super-God-Mode#33]
### Not a Duplicate Issue

- [X] I have searched the existing issues and confirmed this is not a duplicate.

### Script Stops Early or Doesn't Run  (If applicable)

Crashes/stops immediately BEFORE the GUI

### Script Finishes But With a Problem (If applicable)

Not applicable

### What happened?

This is the error I got when I ran the bat, I even tried just running the .ps1 folder but still, it didn't work.
[Error.txt](https://github.com/user-attachments/files/16900579/Error.txt)

### Script Version

1.2.2

### Steps or conditions to reproduce

1.  Windows 11 Home
2.  Idk my computer is prob broken or smth
3. get error

### Windows Version

Windows 11

### How did you run the script?

GUI via launcher batch file

**Comment by ThioJoe** [comment]
Yep the problem is you're in constrained language mode. You can read about that here in the wiki: https://github.com/ThioJoe/Windows-Super-God-Mode/wiki/Frequently-Asked-Questions#im-getting-an-error-such-as-cannot-add-type-definition-of-new-types-is-not-supported-in-this-language-mode

Basically there are 3 possible reasons powershell is in that mode:

- Having any AppLocker script rules set up
- Having the __PSLockDownPolicy environment variable set
- Having a Windows Defender Application Control policy set up (Also Smart App Control enabled, which uses WDAC)

If I had to guess, it would be the 2nd one.
